language: haskell

install:
  - cabal install --only-dependencies -f tests

script:
  - cabal configure -f tests && cabal build && ./dist/build/narrative-tests/narrative-tests

notifications:
  email:
    - jedahu@gmail.com
